version: '3'
services:
  fluentbit:
    container_name: fluentbit-aggregator
    image: fluent/fluent-bit:3.0
    ports:
      - 2022:2022
    volumes:
      - ./config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    env_file:
      - .env
    
    networks:
      - multi-node-setup-network

networks:
  multi-node-setup-network:
    external: true
