version: '3'
services:
  fluentbit-forwarder:
    restart: always
    container_name: fluentbit-forwarder
    image: fluent/fluent-bit:3.0
    ports:
      - 2021:2021 # Forwarder port
      - 4318:4318 # OpenTelemetry port
    volumes:
      # fluentbit forwarding configuration
      - ./config/fluent-bit-forwarder-config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

      # For monitoring host metrics inside the container
      - /proc:/host/proc
      - /sys:/host/sys

    depends_on:
      - opensearch-node1
  
  fluentbit-aggregator:
    restart: always
    container_name: fluentbit-aggregator
    image: fluent/fluent-bit:3.0
    ports:
      - 2022:2022 # Collector port
    volumes:
      # fluentbit collector configuration
      - ./config/fluent-bit-aggregator-config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
    
    depends_on:
      - fluentbit-forwarder

  jaeger:
    restart: always
    image: jaegertracing/all-in-one:1.56
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "6831:6831/udp"
      - "14269:14269"
      - "4444:4317"
      - "4445:4318"  

    environment:
      - SPAN_STORAGE_TYPE=opensearch
      - ES_TAGS_AS_FIELDS_ALL=true
      - ES_USERNAME=admin
      - ES_PASSWORD=admin
      - ES_TLS_SKIP_HOST_VERIFY=false
      - ES_SERVER_URLS=http://opensearch-node1:9200 
    
    depends_on:
      - fluentbit-aggregator
  
  opensearch-node1:
    restart: always
    image: opensearchproject/opensearch:2.13.0
    container_name: opensearch-node1
    environment:
      - cluster.name=opensearch-cluster # Name the cluster
      - node.name=opensearch-node1 # Name the node that will run in this container
      - discovery.seed_hosts=opensearch-node1 # Nodes to look for when discovering the cluster
      - cluster.initial_cluster_manager_nodes=opensearch-node1 # Nodes eligibile to serve as cluster manager
      - bootstrap.memory_lock=true # Disable JVM heap memory swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # Set min and max JVM heap sizes to at least 50% of system RAM
      - "DISABLE_INSTALL_DEMO_CONFIG=true" # Prevents execution of bundled demo script which installs demo certificates and security configurations to OpenSearch
      - "DISABLE_SECURITY_PLUGIN=true" # Disables Security plugin
    ulimits:
      memlock:
        soft: -1 # Set memlock to unlimited (no soft or hard limit)
        hard: -1
      nofile:
        soft: 65536 # Maximum number of open files for the opensearch user - set to at least 65536
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data # Creates volume called opensearch-data1 and mounts it to the container
    ports:
      - 9200:9200 # REST API
      - 9600:9600 # Performance Analyzer
  
  opensearch-dashboards:
    restart: always
    image: opensearchproject/opensearch-dashboards:2.13.0
    container_name: opensearch-dashboards
    ports:
      - 5601:5601 # Map host port 5601 to container port 5601
    expose:
      - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch-node1:9200"]'
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true" # disables security dashboards plugin in OpenSearch Dashboards

  hotrod:
    restart: always
    image: jaegertracing/example-hotrod:1.56
    ports:
      - "8080:8080"
      - "8083:8083"
    command: ["all"]
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://fluentbit-forwarder:4318
    
    depends_on:
      - jaeger

volumes:
  opensearch-data1: